# Generated by Django 2.1.2 on 2018-10-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(related_name='groups', to='quizz.Person'),
        ),
    ]
