# Generated by Django 2.1.2 on 2018-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_group_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='énoncé de la question', unique=True, verbose_name='énoncé')),
                ('slug', models.SlugField(help_text="slug de la question (basé sur l'énoncé)", max_length=256, unique=True, verbose_name='slug')),
                ('answers', models.TextField(help_text='réponses à la question séparées par des ----', verbose_name='réponses')),
                ('correct_answers', models.CharField(help_text='numéro des réponses correctes à la question séparées par des virgules, démarrant à 0', max_length=10, verbose_name='réponses correctes')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['statement'],
            },
        ),
    ]
