# Generated by Django 2.1.2 on 2018-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nom du quizz', max_length=128, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(help_text='slug du quizz (basé sur le nom)', max_length=150, unique=True, verbose_name='slug')),
                ('random_question_order', models.BooleanField(default=True, help_text='est-ce que les questions seront posées en ordre aléatoire', verbose_name='ordre aléatoire des questions')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='quizz.Question')),
            ],
            options={
                'verbose_name': 'Quizz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['name'],
            },
        ),
    ]
