# Generated by Django 2.1.2 on 2018-10-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_quizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text="date d'envoi du quizz à un groupe", unique=True, verbose_name="date d'envoi du quizz")),
                ('group', models.ForeignKey(help_text='groupe destinataire du quizz', on_delete=django.db.models.deletion.CASCADE, related_name='quizz_sendings', to='quizz.Group', verbose_name='groupe')),
                ('quizz', models.ForeignKey(help_text='quizz à envoyer', on_delete=django.db.models.deletion.CASCADE, related_name='quizz_sendings', to='quizz.Quizz', verbose_name='quizz')),
            ],
            options={
                'verbose_name': 'Envoi de quizz',
                'verbose_name_plural': 'Envois de quizz',
                'ordering': ['date'],
            },
        ),
    ]
