# Generated by Django 2.1.2 on 2018-10-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_quizzsending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(help_text='numéro des réponses choisies à la question séparées par des virgules, démarrant à 0', max_length=20, verbose_name='réponses choisies')),
                ('person', models.ForeignKey(help_text='personne questionnée', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizz.Person', verbose_name='personne questionnée')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses à des questions',
                'ordering': ['quizz_sending', 'person', 'question'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizzsending',
            options={'ordering': ['-date'], 'verbose_name': 'Envoi de quizz', 'verbose_name_plural': 'Envois de quizz'},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(help_text='numéro des réponses correctes à la question séparées par des virgules, démarrant à 0', max_length=20, verbose_name='réponses correctes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='question posée', on_delete=django.db.models.deletion.CASCADE, related_name='sent_answers', to='quizz.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quizz_sending',
            field=models.ForeignKey(help_text='envoi de quizz', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizz.QuizzSending', verbose_name='envoi de quizz'),
        ),
    ]
