# Generated by Django 2.1.2 on 2018-11-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_question_auto_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
