# Generated by Django 2.1.2 on 2019-01-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0010_auto_20181101_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizz',
            options={'ordering': ['slug'], 'verbose_name': 'Quizz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
