# Generated by Django 2.1.2 on 2019-03-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_auto_20190124_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(help_text="Nom du bilan, doit pouvoir faire partie d'une URL", max_length=20, verbose_name='Nom du bilan')),
                ('email', models.EmailField(blank=True, help_text='Adresse email', max_length=254, verbose_name='Adresse email')),
                ('easiest', models.TextField(blank=True, help_text='Cette année, le plus facile a été', max_length=1000, verbose_name='Le plus facile')),
                ('hardest', models.TextField(blank=True, help_text='Cette année, le plus difficile a été', max_length=1000, verbose_name='Le plus difficile')),
                ('funniest', models.TextField(blank=True, help_text='Cette année, le plus amusant a été', max_length=1000, verbose_name='Le plus amusant')),
                ('most_boring', models.TextField(blank=True, help_text='Cette année, le plus ennuyant a été', max_length=1000, verbose_name='Le plus ennuyant')),
                ('most_regrettable', models.TextField(blank=True, help_text='Cette année, le plus regrettable a été', max_length=1000, verbose_name='Le plus regrettable')),
                ('most_original', models.TextField(blank=True, help_text='Cette année, le plus original a été', max_length=1000, verbose_name='Le plus original')),
                ('most_interesting', models.TextField(blank=True, help_text='Cette année, le plus intéressant a été', max_length=1000, verbose_name='Le plus intéressant')),
                ('least_interesting', models.TextField(blank=True, help_text='Cette année, le moins intéressant a été', max_length=1000, verbose_name='Le moins intéressant')),
                ('suggestions', models.TextField(blank=True, help_text='Propositions améliorer le cours', max_length=1000, verbose_name="Suggestions d'amélioration")),
            ],
        ),
    ]
