# Generated by Django 2.1.2 on 2019-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0013_auto_20190309_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanswer',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email (facultative)', max_length=254, verbose_name='Adresse email'),
        ),
    ]
