# Generated by Django 2.1.2 on 2019-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0014_auto_20190309_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswer',
            name='teacher_appreciation',
            field=models.TextField(blank=True, help_text='Remarques et appréciations sur le prof', max_length=1000, verbose_name='Remarques sur le prof'),
        ),
    ]
