# Generated by Django 2.1.2 on 2019-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0015_reviewanswer_teacher_appreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanswer',
            name='suggestions',
            field=models.TextField(blank=True, help_text='Propositions pour améliorer le cours', max_length=1000, verbose_name="Suggestions d'amélioration"),
        ),
    ]
