# Generated by Django 2.2.7 on 2020-02-22 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0017_quizzsending_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzsending',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2099, 12, 31, 23, 59, tzinfo=utc), help_text='date de fin du quizz pour un groupe', verbose_name='date de fin du quizz'),
        ),
    ]
