# Generated by Django 4.1 on 2022-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0020_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizzsending",
            name="started",
            field=models.BooleanField(
                default=False,
                help_text="est-ce que ce quiz est démarré",
                verbose_name="quiz démarré",
            ),
        ),
    ]
