# Generated by Django 4.1 on 2022-08-10 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0021_quizzsending_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizzsending",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2099, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                ),
                help_text="date de fin du quizz pour un groupe",
                verbose_name="date de fin du quizz",
            ),
        ),
    ]
